apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-logging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: storemesh-platform
    storemesh.io/optional: "true"
spec:
  project: storemesh
  source:
    repoURL: https://github.com/sartim/storemesh-argocd-repo
    targetRevision: main
    path: manifests/eck-logging
  destination:
    server: https://kubernetes.default.svc
    namespace: storemesh-logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
