apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-mesh-policy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/part-of: storemesh-platform
    storemesh.io/optional: "true"
spec:
  project: storemesh
  source:
    repoURL: https://github.com/sartim/storemesh-argocd-repo
    targetRevision: main
    path: manifests/istio-mesh
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
