apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: storemesh-platform
    storemesh.io/optional: "true"
spec:
  project: storemesh
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 88.5.4
    helm:
      values: |
        crds:
          enabled: true
        grafana:
          enabled: true
        alertmanager:
          enabled: true
        prometheus:
          prometheusSpec:
            retention: 7d
            serviceMonitorSelectorNilUsesHelmValues: false
  destination:
    server: https://kubernetes.default.svc
    namespace: storemesh-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
