apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storemesh-keycloak
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: storemesh-platform
    storemesh.io/optional: "true"
spec:
  project: storemesh
  source:
    repoURL: https://github.com/sartim/storemesh-helm-repo
    targetRevision: main
    path: storemesh-keycloak
    helm:
      values: |
        replicaCount: 1
        admin:
          existingSecret: storemesh-keycloak-admin
          passwordKey: password
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: storemesh-keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
