apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storemesh-bff
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: storemesh
spec:
  project: storemesh
  source:
    repoURL: https://github.com/sartim/storemesh-helm-repo
    targetRevision: main
    path: storemesh-bff
    helm:
      values: |
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: storemesh-bff
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
