apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storemesh-staging-frontend
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: storemesh
    storemesh.io/environment: staging
spec:
  project: storemesh
  source:
    repoURL: https://github.com/sartim/storemesh-helm-repo
    targetRevision: main
    path: storemesh-frontend
    helm:
      values: |
        nameOverride: storemesh-staging-frontend
        image:
          repository: storemesh-frontend
          tag: 0.1.2-staging
          pullPolicy: IfNotPresent
        istio:
          host: staging.storemesh.local
  destination:
    server: https://kubernetes.default.svc
    namespace: storemesh-staging-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
