apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: storemesh-platform
    storemesh.io/optional: "true"
spec:
  project: storemesh
  source:
    repoURL: https://grafana-community.github.io/helm-charts
    chart: tempo
    targetRevision: 2.3.0
    helm:
      values: |
        replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 128Mi
        persistence:
          enabled: true
          size: 10Gi
        serviceMonitor:
          enabled: true
        tempo:
          retention: 24h
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
  destination:
    server: https://kubernetes.default.svc
    namespace: storemesh-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
